In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# from src.models import *
from ilan_src.models import *
from src.dataloader import *
from src.utils import *
from src.evaluation import *

import xarray as xr
import numpy as np
import matplotlib.pyplot as plt

In [4]:
DATADRIVE = '/home/jupyter/data/'

In [7]:
ds_train = TiggeMRMSDataset(
    tigge_dir=f'{DATADRIVE}/tigge/32km/',
    tigge_vars=['total_precipitation'],
    mrms_dir=f'{DATADRIVE}/mrms/4km/RadarOnly_QPE_06H/',
    rq_fn=f'{DATADRIVE}/mrms/4km/RadarQuality.nc',
    data_period=('2018-01', '2018-01'),
    first_days=5,
)

/opt/conda/envs/ilan/lib/python3.9/site-packages/xarray/core/indexing.py:1379: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  return self.array[key]


Loading data


In [8]:
ds_train.overlap_times

array(['2018-01-01T12:00:00.000000000', '2018-01-02T12:00:00.000000000',
       '2018-01-03T12:00:00.000000000', '2018-01-04T12:00:00.000000000',
       '2018-01-05T12:00:00.000000000'], dtype='datetime64[ns]')

In [9]:
ds_train.idxs

array([[  0,   0,   0],
       [  0,   0,   1],
       [  0,   0,   2],
       ...,
       [  4,  72, 129],
       [  4,  73, 127],
       [  4,  73, 128]])

In [10]:
ds_train.tigge

<xarray.DataArray (variable: 1, valid_time: 5, lat: 93, lon: 172)>
array([[[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          3.47072153e-03, 3.63584574e-03, 2.73952602e-03],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          3.14714585e-03, 3.50153549e-03, 3.54822850e-03],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          2.54888151e-03, 2.28819293e-03, 3.22806070e-03],
         ...,
         [7.46481679e-02, 5.68432619e-02, 8.61585127e-02, ...,
          2.30318796e-02, 3.03966184e-02, 3.53431534e-02],
         [3.36016250e-02, 3.94712206e-02, 5.38759011e-02, ...,
          3.66379618e-02, 3.98821621e-02, 3.77205135e-02],
         [3.06574291e-02, 5.55112757e-02, 7.87316815e-02, ...,
          2.40828618e-02, 3.05556860e-02, 2.94586623e-02]],

        [[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          8.55906369e-04, 9.59912284e-04, 7.72822578e-04],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          8.01584713e-04, 6.06885349e-04, 3.58837227e-04],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          5.65692655e-04, 2.77907686e-04, 9.66936914e-05],
...
         [3.41008536e-04, 1.02109301e-03, 9.16755568e-04, ...,
          1.20783039e-02, 1.69582148e-02, 4.89138273e-02],
         [1.75928661e-03, 1.16653410e-03, 6.49698131e-04, ...,
          4.72185113e-02, 3.56376981e-02, 2.90295033e-02],
         [7.11966657e-04, 5.44924202e-04, 9.55887983e-04, ...,
          5.26541423e-02, 4.22067458e-02, 1.18767283e-02]],

        [[1.04540236e-01, 1.32165306e-01, 8.87790471e-02, ...,
          5.65900443e-02, 5.96236623e-02, 5.57879244e-02],
         [7.69391330e-02, 1.15477201e-01, 9.58135690e-02, ...,
          6.20122456e-02, 5.75924568e-02, 5.60602267e-02],
         [1.42148522e-01, 8.28910189e-02, 5.25327027e-02, ...,
          5.47958902e-02, 5.89743610e-02, 5.75227979e-02],
         ...,
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          8.25585490e-03, 2.07875061e-02, 7.16076842e-02],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          2.82333554e-02, 1.21835358e-01, 1.73374159e-01],
         [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
          4.21204683e-02, 1.38898485e-01, 1.03670284e-01]]]])
Coordinates:
    lead_time   timedelta64[ns] 12:00:00
    init_time   (valid_time) datetime64[ns] 2018-01-01 2018-01-02 ... 2018-01-05
  * lon         (lon) float64 235.2 235.5 235.8 236.2 ... 289.3 289.6 289.9
  * lat         (lat) float64 49.68 49.36 49.04 48.72 ... 21.2 20.88 20.56 20.24
  * valid_time  (valid_time) datetime64[ns] 2018-01-01T12:00:00 ... 2018-01-0...
  * variable    (variable) <U2 'tp'

In [11]:
ds_train.mrms

<xarray.DataArray 'tp' (time: 5, lat: 750, lon: 1376)>
array([[[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
...
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]],

       [[0.00058133, 0.00162772, 0.0030229 , ..., 0.00511568,
         0.00627834, 0.00813859],
        [0.00197651, 0.00360423, 0.00255784, ..., 0.00558075,
         0.00569701, 0.00988257],
        [0.00209278, 0.00244158, 0.00162772, ..., 0.00592954,
         0.00697593, 0.01127776],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ],
        [0.        , 0.        , 0.        , ..., 0.        ,
         0.        , 0.        ]]])
Coordinates:
  * time       (time) datetime64[ns] 2018-01-01T12:00:00 ... 2018-01-05T12:00:00
  * lat        (lat) float64 50.0 49.96 49.92 49.88 ... 20.16 20.12 20.08 20.04
  * lon        (lon) float64 235.0 235.0 235.1 235.1 ... 289.9 289.9 290.0 290.0
    lead_time  timedelta64[ns] 12:00:00

In [14]:
idx = 0
time_idx, lat_idx, lon_idx = ds_train.idxs[idx]
time_idx, lat_idx, lon_idx

(0, 0, 0)

In [15]:
lat_slice = slice(lat_idx-ds_train.pad_tigge, lat_idx + ds_train.patch_tigge + ds_train.pad_tigge)
lon_slice = slice(lon_idx-ds_train.pad_tigge, lon_idx + ds_train.patch_tigge + ds_train.pad_tigge)

In [18]:
X = ds_train.tigge.isel(
    valid_time=time_idx,
    lat=lat_slice,
    lon=lon_slice
)
X

<xarray.DataArray (variable: 1, lat: 16, lon: 16)>
array([[[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
        [8.05083636e-05, 6.88102577e-06, 1.26956719e-03, 4.86517171e-03,
         5.79673226e-03, 1.57247345e-04, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         3.29109275e-09, 4.30050149e-05, 5.89006658e-05, 5.38657675e-06],
...
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 9.52634632e-06, 5.81019827e-05, 9.68404855e-06,
         6.89288781e-05, 1.32837584e-04, 1.51829878e-04, 7.15632228e-05],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 6.56403182e-10,
         1.35175309e-05, 1.36541833e-04, 4.28693062e-04, 2.46550816e-04,
         6.76335244e-05, 9.70425113e-05, 1.48367978e-04, 1.00466903e-04],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 1.93018033e-05, 1.73504788e-04, 3.46201195e-04,
         2.24098294e-04, 2.44957564e-04, 2.15985607e-04, 2.29826986e-04],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 1.70057164e-04, 1.88389647e-04,
         1.42644406e-04, 1.45329447e-04, 1.88574659e-04, 6.72477418e-05],
        [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
         0.00000000e+00, 2.59509941e-05, 5.22690927e-04, 5.73841568e-04,
         3.62508655e-04, 4.25197933e-04, 1.84984053e-04, 1.93734527e-05]]])
Coordinates:
    lead_time   timedelta64[ns] 12:00:00
    init_time   datetime64[ns] 2018-01-01
  * lon         (lon) float64 235.2 235.5 235.8 236.2 ... 239.4 239.7 240.0
  * lat         (lat) float64 49.68 49.36 49.04 48.72 ... 45.84 45.52 45.2 44.88
    valid_time  datetime64[ns] 2018-01-01T12:00:00
  * variable    (variable) <U2 'tp'

In [19]:
lat_slice = slice(lat_idx * ds_train.ratio, lat_idx * ds_train.ratio + ds_train.patch_mrms)
lon_slice = slice(lon_idx * ds_train.ratio, lon_idx * ds_train.ratio + ds_train.patch_mrms)

In [20]:
y = ds_train.mrms.isel(
    time=time_idx,
    lat=lat_slice,
    lon=lon_slice
)
y

<xarray.DataArray 'tp' (lat: 128, lon: 128)>
array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.00116266],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])
Coordinates:
    time       datetime64[ns] 2018-01-01T12:00:00
  * lat        (lat) float64 50.0 49.96 49.92 49.88 ... 45.04 45.0 44.96 44.92
  * lon        (lon) float64 235.0 235.0 235.1 235.1 ... 240.0 240.0 240.0 240.1
    lead_time  timedelta64[ns] 12:00:00